version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21
    commands:
      # Install dependencies
      - npm install

  build:
    commands:
      # Run the build script
      - npm run build

artifacts:
  files:
    - public/**/*  # All files under the public directory
    - src/**/*      # All files under the src directory
    - package.json  # Include the package.json for dependency info
    - appspec.yml    # Include appspec file for CodeDeploy
    - scripts/**/*   # Include all scripts
